server {
    listen 8081;
    server_name _;
    resolver 127.0.0.11 valid=30s ipv6=off;

    location / {
        set $netbox_upstream http://netbox:8080;
        proxy_pass $netbox_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-authentik-username $http_x_authentik_username;
        proxy_set_header X-authentik-email $http_x_authentik_email;
        proxy_set_header X-authentik-name $http_x_authentik_name;
        proxy_set_header X-authentik-groups $http_x_authentik_groups;
    }
}
