ARG NETBOX_IMAGE=netboxcommunity/netbox:v4.5.7
FROM ${NETBOX_IMAGE}

COPY plugin_requirements.txt /opt/netbox/plugin_requirements.txt
RUN /usr/local/bin/uv pip install   --python /opt/netbox/venv/bin/python   -r /opt/netbox/plugin_requirements.txt

COPY configuration/extra.py /etc/netbox/config/extra.py
COPY configuration/plugins.py /etc/netbox/config/plugins.py
RUN mkdir -p /opt/netbox/netbox/static/netbox_topology_views/img
RUN SECRET_KEY=dummydummydummydummydummydummydummydummydummydummy \
    /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input
